In [1]:
from itertools import product

import numpy as np

from fsa_generator import random_ngram

In [2]:
A = random_ngram(2, 2, 1)

In [3]:
A

PFSA(n_states=3, n_symbols=2)

T[0]: 
[[0.         0.69905073 0.        ]
 [0.         0.68449943 0.        ]
 [0.         0.42738033 0.        ]]

T[1]: 
[[0.         0.         0.20094927]
 [0.         0.         0.21550057]
 [0.         0.         0.47261967]]

T: 
[[0.         0.69905073 0.20094927]
 [0.         0.68449943 0.21550057]
 [0.         0.42738033 0.47261967]]

T*: 
[[ 1.          6.11871124  2.88128876]
 [-0.          7.09912358  2.90087642]
 [ 0.          5.75301277  4.24698723]]

λ = [1. 0. 0.]

ρ = [0.1 0.1 0.1]

In [10]:
D = A.sample(10000)

In [5]:
A.is_probabilistic

True

In [6]:
A.entropy

12.340954227221298

In [7]:
A.local_entropy(m=10)

45.76558069326644